const router = require('express').Router();
const { spotifyFetch, spotifyPost, refreshAccessToken } = require('../lib/spotifyClient');

const { SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET } = process.env;

async function ensureToken(req, res, next) {
  if (!req.session.accessToken) return res.status(401).json({ error: 'Not authenticated' });

  if (Date.now() > req.session.expiresAt - 60_000) {
    try {
      const data = await refreshAccessToken(
        SPOTIFY_CLIENT_ID,
        SPOTIFY_CLIENT_SECRET,
        req.session.refreshToken
      );
      req.session.accessToken = data.access_token;
      req.session.expiresAt = Date.now() + data.expires_in * 1000;
      if (data.refresh_token) req.session.refreshToken = data.refresh_token;
    } catch {
      req.session.destroy();
      return res.status(401).json({ error: 'Token refresh failed' });
    }
  }
  next();
}

router.get('/now-playing', ensureToken, async (req, res) => {
  try {
    const playing = await spotifyFetch(
      'https://api.spotify.com/v1/me/player/currently-playing',
      req.session.accessToken
    );

    if (!playing || !playing.item) return res.json({ isPlaying: false });

    const track = playing.item;
    const artistId = track.artists[0]?.id;

    const [features, artist] = await Promise.all([
      spotifyFetch(
        `https://api.spotify.com/v1/audio-features/${track.id}`,
        req.session.accessToken
      ).catch(() => null),
      artistId
        ? spotifyFetch(`https://api.spotify.com/v1/artists/${artistId}`, req.session.accessToken).catch(() => null)
        : null,
    ]);

    res.json({
      isPlaying: true,
      track: {
        id: track.id,
        title: track.name,
        artist: track.artists.map(a => a.name).join(', '),
        albumArt: track.album.images[0]?.url ?? null,
        albumName: track.album.name,
      },
      audioFeatures: features
        ? {
            energy: features.energy,
            tempo: features.tempo,
            valence: features.valence,
            danceability: features.danceability,
            acousticness: features.acousticness,
            instrumentalness: features.instrumentalness,
          }
        : null,
      genres: artist?.genres ?? [],
    });
  } catch (err) {
    console.error('now-playing error:', err);
    if (err.status === 401) return res.status(401).json({ error: 'Unauthorized' });
    res.status(500).json({ error: 'Internal error' });
  }
});

router.post('/playlist', ensureToken, async (req, res) => {
  const {
    themeName, themeEmoji, seedTrackId,
    targetEnergy, targetValence, targetDanceability, targetAcousticness,
    keywords,
  } = req.body;

  const token = req.session.accessToken;

  try {
    // 1. Get 20 recommended tracks (fallback to search if API is restricted)
    let trackUris;
    try {
      const recsUrl =
        `https://api.spotify.com/v1/recommendations?limit=20&seed_tracks=${seedTrackId}` +
        `&target_energy=${targetEnergy}&target_valence=${targetValence}` +
        `&target_danceability=${targetDanceability}&target_acousticness=${targetAcousticness}`;
      const recs = await spotifyFetch(recsUrl, token);
      trackUris = recs.tracks.map(t => t.uri);
    } catch {
      // Fallback: search by genre keywords
      const q = encodeURIComponent((keywords ?? []).slice(0, 2).join(' ') || themeName);
      const results = await spotifyFetch(
        `https://api.spotify.com/v1/search?q=${q}&type=track&limit=20`,
        token
      );
      trackUris = results.tracks.items.map(t => t.uri);
    }

    // 2. Get user ID
    const user = await spotifyFetch('https://api.spotify.com/v1/me', token);

    // 3. Create playlist
    const playlistName = `VibeSync: ${themeName} ${themeEmoji}`;
    const playlist = await spotifyPost(
      `https://api.spotify.com/v1/users/${user.id}/playlists`,
      token,
      { name: playlistName, public: true, description: 'Generated by VibeSync ✦' }
    );

    // 4. Add tracks
    await spotifyPost(
      `https://api.spotify.com/v1/playlists/${playlist.id}/tracks`,
      token,
      { uris: trackUris }
    );

    res.json({ playlistUrl: playlist.external_urls.spotify, name: playlistName });
  } catch (err) {
    console.error('playlist error:', err);
    const needsReauth = err.status === 403;
    res.status(err.status || 500).json({ error: 'playlist_failed', needsReauth });
  }
});

module.exports = router;
