export const THEMES = {
  lofi_chill: {
    id: 'lofi_chill',
    name: 'Lofi Chill',
    bg: '#0e1117',
    accent: '#a8d8ea',
    glow: 'rgba(168,216,234,0.28)',
    keywords: ['lo-fi','lofi','chillhop','chill','ambient','study beats','lo fi','bedroom'],
  },
  cyberpunk: {
    id: 'cyberpunk',
    name: 'Cyberpunk',
    bg: '#060212',
    accent: '#00ffff',
    glow: 'rgba(0,255,255,0.32)',
    keywords: ['electronic','synthwave','industrial','electro','future bass','edm','techno','cyber','dnb','drum and bass'],
  },
  cottagecore: {
    id: 'cottagecore',
    name: 'Cottagecore',
    bg: '#0d1a0a',
    accent: '#a8e67a',
    glow: 'rgba(168,230,122,0.28)',
    keywords: ['folk','indie folk','acoustic','cottagecore','country','bluegrass','celtic','irish'],
  },
  dark_academia: {
    id: 'dark_academia',
    name: 'Dark Academia',
    bg: '#100c06',
    accent: '#c9a84c',
    glow: 'rgba(201,168,76,0.28)',
    keywords: ['classical','chamber','neoclassical','baroque','orchestral','opera','score','soundtrack'],
  },
  vaporwave: {
    id: 'vaporwave',
    name: 'Vaporwave',
    bg: '#100122',
    accent: '#ff71ce',
    glow: 'rgba(255,113,206,0.32)',
    keywords: ['vaporwave','dream pop','synthpop','synth pop','chillwave','new wave','retrowave','80s'],
  },
  hype_hyperpop: {
    id: 'hype_hyperpop',
    name: 'Hype / Hyperpop',
    bg: '#080808',
    accent: '#ffff00',
    glow: 'rgba(255,255,0,0.32)',
    keywords: ['hyperpop','pop','trap','phonk','hip hop','rap','drill','dance pop','edm pop'],
  },
  metal_rage: {
    id: 'metal_rage',
    name: 'Metal / Rage',
    bg: '#0a0000',
    accent: '#ff3300',
    glow: 'rgba(255,51,0,0.36)',
    keywords: ['metal','hardcore','death metal','black metal','thrash','heavy metal','grunge','punk','noise','doom'],
  },
  classical_baroque: {
    id: 'classical_baroque',
    name: 'Classical / Baroque',
    bg: '#08061a',
    accent: '#d4af37',
    glow: 'rgba(212,175,55,0.28)',
    keywords: ['classical','baroque','romantic','piano','violin','symphony','concerto','chamber music','early music'],
  },
  rnb_soul: {
    id: 'rnb_soul',
    name: 'R&B / Soul',
    bg: '#0a0509',
    accent: '#ff6b9d',
    glow: 'rgba(255,107,157,0.28)',
    keywords: ['r&b','rnb','soul','neo soul','funk','motown','smooth','contemporary r&b','gospel'],
  },
  indie_folk: {
    id: 'indie_folk',
    name: 'Indie / Folk',
    bg: '#070f0d',
    accent: '#7ec8a4',
    glow: 'rgba(126,200,164,0.28)',
    keywords: ['indie','folk','singer-songwriter','indie rock','alternative','bedroom pop','indie pop','shoegaze'],
  },
  lofi_jazz: {
    id: 'lofi_jazz',
    name: 'Lofi Jazz',
    bg: '#0d0d1a',
    accent: '#d4a843',
    glow: 'rgba(212,168,67,0.28)',
    keywords: ['jazz','bebop','swing','smooth jazz','cool jazz','lofi jazz','jazz hop','nu jazz'],
  },
  kpop: {
    id: 'kpop',
    name: 'K-Pop',
    bg: '#1a0a2e',
    accent: '#ff69b4',
    glow: 'rgba(255,105,180,0.32)',
    keywords: ['k-pop','kpop','korean pop','k pop','j-pop','jpop','city pop'],
  },
  dream_pop: {
    id: 'dream_pop',
    name: 'Dream Pop',
    bg: '#0a0d1f',
    accent: '#c9b1ff',
    glow: 'rgba(201,177,255,0.30)',
    keywords: ['dream pop','shoegaze','ethereal','ambient pop','indie dream','bedroom pop','slowcore'],
  },
  phonk: {
    id: 'phonk',
    name: 'Phonk',
    bg: '#080808',
    accent: '#cc0000',
    glow: 'rgba(200,0,0,0.36)',
    keywords: ['phonk','memphis rap','drift phonk','dark trap','horrorcore'],
  },
  bubblegum_pop: {
    id: 'bubblegum_pop',
    name: 'Bubblegum Pop',
    bg: '#1a0015',
    accent: '#ff85c8',
    glow: 'rgba(255,133,200,0.32)',
    keywords: ['bubblegum pop','teen pop','bubblegum','kawaii','cute pop','electropop'],
  },
  reggae: {
    id: 'reggae',
    name: 'Reggae / Chill',
    bg: '#041a04',
    accent: '#ffd700',
    glow: 'rgba(255,215,0,0.28)',
    keywords: ['reggae','ska','dancehall','dub','roots reggae','reggaeton','tropical'],
  },
  country: {
    id: 'country',
    name: 'Country',
    bg: '#1a0e00',
    accent: '#e8a020',
    glow: 'rgba(232,160,32,0.28)',
    keywords: ['country','americana','bluegrass','country pop','honky tonk','outlaw country','southern rock'],
  },
  afrobeats: {
    id: 'afrobeats',
    name: 'Afrobeats',
    bg: '#1a0800',
    accent: '#ff6b00',
    glow: 'rgba(255,107,0,0.32)',
    keywords: ['afrobeats','afropop','afro','highlife','afrofusion','afro pop','afro house'],
  },
  experimental: {
    id: 'experimental',
    name: 'Experimental',
    bg: '#050510',
    accent: '#00ff88',
    glow: 'rgba(0,255,136,0.30)',
    keywords: ['experimental','avant-garde','noise','glitch','microsound','electroacoustic','art rock','free jazz'],
  },
  edm: {
    id: 'edm',
    name: 'EDM / Rave',
    bg: '#04001a',
    accent: '#00d4ff',
    glow: 'rgba(0,212,255,0.36)',
    keywords: ['edm','house','techno','trance','dubstep','drum and bass','rave','big room','hardstyle','progressive house'],
  },
};

export const THEME_IDS = Object.keys(THEMES);

export const THEME_EMOJI = {
  lofi_chill: '🐱', cyberpunk: '🤖', cottagecore: '🐰',
  dark_academia: '🦉', vaporwave: '👾', hype_hyperpop: '🐸',
  metal_rage: '💀', classical_baroque: '🎼', rnb_soul: '🐻',
  indie_folk: '🐕', lofi_jazz: '🦊', kpop: '🐼',
  dream_pop: '🦋', phonk: '🐺', bubblegum_pop: '🦄',
  reggae: '🌴', country: '🤠', afrobeats: '🦁',
  experimental: '🐙', edm: '🐉',
};
